### ISSUE TITLE
Question: Remove Bootstrap

### ISSUE THREAD

**Issue by mxmtsk** [xkawi/react-universal-saga#3]
Hey xkawi,

thanks for taking the time to update the react-redux-universal-hot-example. It looks very good so far but I wanna get rid of bootstrap completely and only use sass. Could you help me with that and point me to all the locations in the code?

Thanks!

**Comment by xkawi** [comment]
Think you can follow the sequence below, though I haven't really test it yet:
1. start by removing the `bootstrap-loader` from `entry.main` option in `webpack/*.config.js` files
2. If it compiles successfully (`npm run build`), remove bootstrap-related options in `src/theme/style.css` such as the line with `$bootstrap-sass-asset-helper`, `@import ~bootstrap-sass...` and Iconography section at the bottom. Also remove all references to bootstrap mixin from any .scss files (e.g. App.scss).
3. If still can compiles, remove these files, since they are not used anymore: `theme/bootstrap.overrides.scss`, `theme/variables.scss` and `.bootstraprc`
4. remove the Button component imported from react-bootstrap in `components/Explore.js`
5. Finally, to get rid of bootstrap completely, remove bootstrap-related packages: `npm uninstall --save-dev bootstrap-sass bootstrap-loader react-bootstrap react-router-bootstrap`

hope this helps. 😃

**Comment by mxmtsk** [comment]
Yes, perfect! Thanks :)
